
# Configuracion con mysql

# Definimos el driver JDBC para conectar con nuestra instancia de WAMP/MySQL.
# Usamos 'desafio2' como schema .
spring.datasource.url=jdbc:mysql://localhost:3306/desafio2?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# configuracion de  HIBERNATE (ORM)

# 'update': Hibernate valida el esquema de la base de datos y lo actualiza
# automáticamente basado en nuestras entidades (POJOs) sin borrar datos previos.
spring.jpa.hibernate.ddl-auto=update

# 'show-sql': Vital para debugging. Imprime en consola las consultas
# que Hibernate genera (INSERT/SELECT/UPDATE). Útil para entender qué ocurre.
spring.jpa.show-sql=true


# configuarion del dialecto

# Fuerza a Hibernate a usar la sintaxis específica de MySQL 8+.
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect